name: Dependency Check

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Dependency Review
        uses: actions/dependency-review-action@v4