name: "testworkflows"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
    runs-on: [self-hosted]
    env:
      OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github'
      PLATFORM_REPO: 'generic-local'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: http://localhost:8081
        with:
          oidc-provider-name: github-jfrog
          oidc-audience: my-aud

      - name: Publish Build info With JFrog CLI
        run: |
          jf rt u file.txt generic-local/file.txt